name: Running Stage Notifier

on:
  schedule:
    - cron: "30 15,21 * * *"
  workflow_dispatch:

jobs:
  run-command:
    name: Run Command
    runs-on: ubuntu-20.04

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure direnv
        uses: HatsuneMiku3939/direnv-action@v1

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc

      - name: Node cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
          aws-region: us-east-1
          role-duration-seconds: 10800

      - name: Get a list of running stages
        id: running-stages
        run: |
          echo "RUNNING_STAGES<<EOF" >> $GITHUB_OUTPUT
          run listRunningStages --string >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Slack Notification - notify of failure reporting on running stages
        uses: rtCamp/action-slack-notify@v2
        if: env.SLACK_WEBHOOK != '' && failure()
        env:
          SLACK_MSG_AUTHOR: ${{ github.repository }}
          SLACK_COLOR: ${{job.status}}
          SLACK_ICON: https://github.com/cmsgov.png?size=48
          SLACK_TITLE: Failure retrieving currently running stages
          SLACK_MESSAGE: Failure retrieving currently running stages
          SLACK_USERNAME: ${{ github.repository }} - ${{ github.workflow }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          MSG_MINIMAL: true

      - name: Slack Notification - notify of currently running stages
        uses: rtCamp/action-slack-notify@v2
        if: env.SLACK_WEBHOOK != '' && steps.running-stages.outputs.RUNNING_STAGES
        env:
          SLACK_MSG_AUTHOR: ${{ github.repository }}
          SLACK_COLOR: ${{job.status}}
          SLACK_ICON: https://github.com/cmsgov.png?size=48
          SLACK_TITLE: Currently Running Stages
          SLACK_MESSAGE: ${{ steps.running-stages.outputs.RUNNING_STAGES }}
          SLACK_USERNAME: ${{ github.repository }} - ${{ github.workflow }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          MSG_MINIMAL: true
